import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Institutional Terminal design tokens
        "surface-base": "#080a0f",
        "surface-1": "#0c0f17",
        "surface-2": "#111520",
        "surface-3": "#161b27",
        "border-subtle": "#1c2235",
        "border-active": "#2a3350",
        "accent-primary": "#00ff88",
        "accent-secondary": "#0ea5e9",
        "accent-warn": "#f59e0b",
        "accent-danger": "#ff3b5c",
        "accent-elite": "#a78bfa",
        "text-primary": "#e8edf5",
        "text-secondary": "#8892a4",
        "text-tertiary": "#4a5568",
        // Legacy aliases (used elsewhere in codebase)
        bg: "#06080d",
        sidebar: "#080b11",
        card: "#0c1018",
        border: "#1a2030",
        text: "#e8edf5",
        muted: "#5a6580",
        dimmed: "#3a4560",
        quote: "#a0afc0",
        green: "#00e5b0",
        red: "#ff4d6d",
        blue: "#0066ff",
        purple: "#b466ff",
        gold: "#f0c040",
      },
      fontFamily: {
        display: ["Syne", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        body: ["DM Sans", "sans-serif"],
        heading: ["var(--font-bebas)", "sans-serif"],
        sans: ["var(--font-dm-sans)", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
  safelist: [
    "font-display",
    "font-mono",
    "font-body",
    "font-heading",
    "font-sans",
    "text-text",
    "text-muted",
    "text-dimmed",
    "text-quote",
    "text-green",
    "text-red",
    "text-blue",
    "text-purple",
    "text-gold",
    "text-text-primary",
    "text-text-secondary",
    "text-text-tertiary",
    "bg-bg",
    "bg-sidebar",
    "bg-card",
    "bg-surface-base",
    "bg-surface-1",
    "bg-surface-2",
    "border-border",
    "border-border-subtle",
    "hover:text-text",
    "hover:bg-card",
  ],
};

export default config;
